export default [
  {
    Name: 'Leila Johnson',
    Country: 'Monaco',
    Age: 34,
    Gender: 'female',
    Compensation: 46645,
  },
  {
    Name: 'Mohammad Richmond',
    Country: 'Israel',
    Age: 27,
    Gender: 'female',
    Compensation: 90415,
  },
  {
    Name: 'Kirk Ross',
    Country: 'Nauru',
    Age: 47,
    Gender: 'female',
    Compensation: 13500,
  },
  {
    Name: 'Chandler Mccarty',
    Country: 'Svalbard and Jan Mayen Islands',
    Age: 41,
    Gender: 'female',
    Compensation: 45537,
  },
  {
    Name: 'Noelani Wood',
    Country: 'Bahamas',
    Age: 45,
    Gender: 'female',
    Compensation: 27272,
  },
  {
    Name: 'Declan Salas',
    Country: 'Tonga',
    Age: 55,
    Gender: 'female',
    Compensation: 91443,
  },
  {
    Name: 'Leila Sargent',
    Country: 'Saudi Arabia',
    Age: 26,
    Gender: 'female',
    Compensation: 53951,
  },
  {
    Name: 'Cody Weaver',
    Country: 'India',
    Age: 37,
    Gender: 'female',
    Compensation: 92303,
  },
  {
    Name: 'Dora Lewis',
    Country: 'Estonia',
    Age: 42,
    Gender: 'female',
    Compensation: 93347,
  },
  {
    Name: 'Xanthus Coleman',
    Country: 'Samoa',
    Age: 50,
    Gender: 'female',
    Compensation: 76775,
  },
  {
    Name: 'Raphael Barker',
    Country: 'United Kingdom (Great Britain)',
    Age: 59,
    Gender: 'male',
    Compensation: 51765,
  },
  {
    Name: 'Cara Skinner',
    Country: 'United Arab Emirates',
    Age: 56,
    Gender: 'male',
    Compensation: 17285,
  },
  {
    Name: 'Dominic Estrada',
    Country: 'Viet Nam',
    Age: 36,
    Gender: 'male',
    Compensation: 59684,
  },
  {
    Name: 'Mason May',
    Country: 'Malaysia',
    Age: 56,
    Gender: 'male',
    Compensation: 38666,
  },
  {
    Name: 'Jade Bauer',
    Country: 'Iraq',
    Age: 46,
    Gender: 'male',
    Compensation: 37426,
  },
  {
    Name: 'Hadley Spencer',
    Country: 'Djibouti',
    Age: 38,
    Gender: 'male',
    Compensation: 16376,
  },
  {
    Name: 'Nathan Sykes',
    Country: 'Palau',
    Age: 25,
    Gender: 'male',
    Compensation: 88937,
  },
  {
    Name: 'Lillith Simpson',
    Country: 'Mongolia',
    Age: 53,
    Gender: 'male',
    Compensation: 20958,
  },
  {
    Name: 'Anne Warner',
    Country: 'United Arab Emirates',
    Age: 48,
    Gender: 'male',
    Compensation: 15196,
  },
  {
    Name: 'Kevyn Phelps',
    Country: 'Malaysia',
    Age: 25,
    Gender: 'male',
    Compensation: 74706,
  },
  {
    Name: 'Beck Craft',
    Country: 'France',
    Age: 37,
    Gender: 'female',
    Compensation: 61995,
  },
  {
    Name: 'Felix Davenport',
    Country: 'Marshall Islands',
    Age: 50,
    Gender: 'female',
    Compensation: 32992,
  },
  {
    Name: 'Lacota Watts',
    Country: 'Venezuela',
    Age: 33,
    Gender: 'female',
    Compensation: 53299,
  },
  {
    Name: 'Shaeleigh Gould',
    Country: 'Japan',
    Age: 41,
    Gender: 'female',
    Compensation: 73879,
  },
  {
    Name: 'Mason Elliott',
    Country: 'Tanzania',
    Age: 31,
    Gender: 'female',
    Compensation: 51384,
  },
  {
    Name: 'Maggie Nash',
    Country: 'Antarctica',
    Age: 53,
    Gender: 'female',
    Compensation: 12541,
  },
  {
    Name: 'Inez Frye',
    Country: 'Puerto Rico',
    Age: 46,
    Gender: 'female',
    Compensation: 98404,
  },
  {
    Name: 'Armando Hopper',
    Country: 'Comoros',
    Age: 42,
    Gender: 'female',
    Compensation: 93303,
  },
  {
    Name: 'Isadora Howell',
    Country: 'Morocco',
    Age: 39,
    Gender: 'female',
    Compensation: 98844,
  },
  {
    Name: 'Armand Greene',
    Country: 'Cayman Islands',
    Age: 40,
    Gender: 'female',
    Compensation: 31347,
  },
  {
    Name: 'Jaquelyn Ware',
    Country: 'Iran',
    Age: 45,
    Gender: 'male',
    Compensation: 60183,
  },
  {
    Name: 'Adria Hunter',
    Country: 'Botswana',
    Age: 42,
    Gender: 'male',
    Compensation: 58495,
  },
  {
    Name: 'Kay Mckenzie',
    Country: 'Libya',
    Age: 42,
    Gender: 'male',
    Compensation: 48702,
  },
  {
    Name: 'Kasimir Rodriquez',
    Country: 'United Kingdom (Great Britain)',
    Age: 46,
    Gender: 'male',
    Compensation: 23400,
  },
  {
    Name: 'Lacy Todd',
    Country: 'Congo (Brazzaville)',
    Age: 36,
    Gender: 'male',
    Compensation: 12267,
  },
  {
    Name: 'Charles Ayala',
    Country: 'Croatia',
    Age: 31,
    Gender: 'male',
    Compensation: 79626,
  },
  {
    Name: 'Rajah Norris',
    Country: 'Equatorial Guinea',
    Age: 60,
    Gender: 'male',
    Compensation: 73599,
  },
  {
    Name: 'Inez Flynn',
    Country: 'Saint Pierre and Miquelon',
    Age: 46,
    Gender: 'male',
    Compensation: 35911,
  },
  {
    Name: 'Ferris Todd',
    Country: 'Burundi',
    Age: 40,
    Gender: 'male',
    Compensation: 77356,
  },
  {
    Name: 'Marsden Oliver',
    Country: 'Tokelau',
    Age: 34,
    Gender: 'male',
    Compensation: 96317,
  },
  {
    Name: 'Jana Austin',
    Country: 'Bahamas',
    Age: 55,
    Gender: 'female',
    Compensation: 31823,
  },
  {
    Name: 'Gloria Jensen',
    Country: 'Dominican Republic',
    Age: 44,
    Gender: 'female',
    Compensation: 89146,
  },
  {
    Name: 'Lunea Gutierrez',
    Country: 'Lithuania',
    Age: 38,
    Gender: 'female',
    Compensation: 49879,
  },
  {
    Name: 'Martha Wynn',
    Country: 'Martinique',
    Age: 28,
    Gender: 'female',
    Compensation: 47764,
  },
  {
    Name: 'Darius Bartlett',
    Country: 'Greenland',
    Age: 47,
    Gender: 'female',
    Compensation: 73050,
  },
  {
    Name: 'Price Ward',
    Country: 'Mauritius',
    Age: 55,
    Gender: 'female',
    Compensation: 48600,
  },
  {
    Name: 'Ray Johnston',
    Country: 'Kiribati',
    Age: 58,
    Gender: 'female',
    Compensation: 49957,
  },
  {
    Name: 'Jena Rivers',
    Country: 'Hong Kong',
    Age: 53,
    Gender: 'female',
    Compensation: 78854,
  },
  {
    Name: 'Jermaine Cherry',
    Country: 'Belgium',
    Age: 31,
    Gender: 'female',
    Compensation: 82409,
  },
  {
    Name: 'Jenna Carver',
    Country: 'Moldova',
    Age: 54,
    Gender: 'female',
    Compensation: 31202,
  },
  {
    Name: 'Gary Adkins',
    Country: 'Denmark',
    Age: 36,
    Gender: 'male',
    Compensation: 55941,
  },
  {
    Name: 'Brian Mcmillan',
    Country: 'Tuvalu',
    Age: 46,
    Gender: 'male',
    Compensation: 74720,
  },
  {
    Name: 'Alvin Carey',
    Country: 'Russian Federation',
    Age: 54,
    Gender: 'male',
    Compensation: 93473,
  },
  {
    Name: 'Maile Logan',
    Country: 'Qatar',
    Age: 32,
    Gender: 'male',
    Compensation: 49715,
  },
  {
    Name: 'Kuame Ryan',
    Country: 'Sao Tome and Principe',
    Age: 43,
    Gender: 'male',
    Compensation: 31968,
  },
  {
    Name: 'Maya Stout',
    Country: 'Venezuela',
    Age: 47,
    Gender: 'male',
    Compensation: 53885,
  },
  {
    Name: 'Hermione Gibson',
    Country: 'Isle of Man',
    Age: 27,
    Gender: 'male',
    Compensation: 66687,
  },
  {
    Name: 'William Marks',
    Country: 'Azerbaijan',
    Age: 49,
    Gender: 'male',
    Compensation: 90882,
  },
  {
    Name: 'Kareem Porter',
    Country: 'Saint Kitts and Nevis',
    Age: 54,
    Gender: 'male',
    Compensation: 10618,
  },
  {
    Name: 'Mohammad Bishop',
    Country: 'Solomon Islands',
    Age: 55,
    Gender: 'male',
    Compensation: 99194,
  },
  {
    Name: 'Sopoline Scott',
    Country: 'Thailand',
    Age: 33,
    Gender: 'female',
    Compensation: 78457,
  },
  {
    Name: 'Rhona Roy',
    Country: 'Iraq',
    Age: 44,
    Gender: 'female',
    Compensation: 13244,
  },
  {
    Name: 'Leonard Walter',
    Country: 'Macao',
    Age: 36,
    Gender: 'female',
    Compensation: 15268,
  },
  {
    Name: 'Brennan Riddle',
    Country: 'United States',
    Age: 46,
    Gender: 'female',
    Compensation: 65671,
  },
  {
    Name: 'Ruth Phillips',
    Country: 'Åland Islands',
    Age: 25,
    Gender: 'female',
    Compensation: 91380,
  },
  {
    Name: 'Raja Rosales',
    Country: 'Vanuatu',
    Age: 56,
    Gender: 'female',
    Compensation: 73917,
  },
  {
    Name: 'Kyla Lester',
    Country: 'Bhutan',
    Age: 34,
    Gender: 'female',
    Compensation: 84103,
  },
  {
    Name: 'Felicia Benton',
    Country: 'Macao',
    Age: 60,
    Gender: 'female',
    Compensation: 77167,
  },
  {
    Name: 'Alexander Farmer',
    Country: 'Suriname',
    Age: 31,
    Gender: 'female',
    Compensation: 85321,
  },
  {
    Name: 'Arsenio Watson',
    Country: 'Guinea-Bissau',
    Age: 28,
    Gender: 'female',
    Compensation: 59154,
  },
  {
    Name: 'Xavier Hoffman',
    Country: 'Angola',
    Age: 26,
    Gender: 'male',
    Compensation: 81474,
  },
  {
    Name: 'Reece House',
    Country: 'Gambia',
    Age: 43,
    Gender: 'male',
    Compensation: 67951,
  },
  {
    Name: 'Yen Cain',
    Country: 'Sierra Leone',
    Age: 43,
    Gender: 'male',
    Compensation: 48408,
  },
  {
    Name: 'Lynn Sheppard',
    Country: 'Belarus',
    Age: 45,
    Gender: 'male',
    Compensation: 25815,
  },
  {
    Name: 'Kirestin Heath',
    Country: 'Guatemala',
    Age: 56,
    Gender: 'male',
    Compensation: 39300,
  },
  {
    Name: 'Amal Burgess',
    Country: 'Equatorial Guinea',
    Age: 47,
    Gender: 'male',
    Compensation: 32100,
  },
  {
    Name: 'Timothy Pittman',
    Country: 'San Marino',
    Age: 45,
    Gender: 'male',
    Compensation: 79976,
  },
  {
    Name: 'Devin Robinson',
    Country: 'Solomon Islands',
    Age: 54,
    Gender: 'male',
    Compensation: 41069,
  },
  {
    Name: 'Madison Haynes',
    Country: 'Samoa',
    Age: 29,
    Gender: 'male',
    Compensation: 97875,
  },
  {
    Name: 'Jonah Ryan',
    Country: 'Russian Federation',
    Age: 52,
    Gender: 'male',
    Compensation: 40752,
  },
  {
    Name: 'Rahim Glover',
    Country: 'Guadeloupe',
    Age: 31,
    Gender: 'female',
    Compensation: 58437,
  },
  {
    Name: 'Vance Mejia',
    Country: 'Zimbabwe',
    Age: 60,
    Gender: 'female',
    Compensation: 15861,
  },
  {
    Name: 'Constance Wilder',
    Country: 'Eritrea',
    Age: 45,
    Gender: 'female',
    Compensation: 80718,
  },
  {
    Name: 'Felix Chase',
    Country: 'Sierra Leone',
    Age: 25,
    Gender: 'female',
    Compensation: 70380,
  },
  {
    Name: 'Shelley Welch',
    Country: 'Timor-Leste',
    Age: 45,
    Gender: 'female',
    Compensation: 76986,
  },
  {
    Name: 'Maryam Hamilton',
    Country: 'Italy',
    Age: 26,
    Gender: 'female',
    Compensation: 20966,
  },
  {
    Name: 'Amity Delacruz',
    Country: 'Dominican Republic',
    Age: 51,
    Gender: 'female',
    Compensation: 15609,
  },
  {
    Name: 'Cara Winters',
    Country: 'Montenegro',
    Age: 59,
    Gender: 'female',
    Compensation: 80415,
  },
  {
    Name: 'Hannah Valentine',
    Country: 'Senegal',
    Age: 58,
    Gender: 'female',
    Compensation: 26281,
  },
  {
    Name: 'Hanna Blanchard',
    Country: 'Luxembourg',
    Age: 35,
    Gender: 'female',
    Compensation: 44136,
  },
  {
    Name: 'Melyssa Johns',
    Country: 'Switzerland',
    Age: 52,
    Gender: 'male',
    Compensation: 78649,
  },
  {
    Name: 'Oscar Justice',
    Country: 'Lithuania',
    Age: 29,
    Gender: 'male',
    Compensation: 84117,
  },
  {
    Name: 'Nevada Obrien',
    Country: 'Hong Kong',
    Age: 39,
    Gender: 'male',
    Compensation: 49052,
  },
  {
    Name: 'Wyatt Chan',
    Country: 'Paraguay',
    Age: 42,
    Gender: 'male',
    Compensation: 81700,
  },
  {
    Name: 'Edward Aguilar',
    Country: 'Dominican Republic',
    Age: 34,
    Gender: 'male',
    Compensation: 18038,
  },
  {
    Name: 'Ruth Blackwell',
    Country: 'Angola',
    Age: 53,
    Gender: 'male',
    Compensation: 34503,
  },
  {
    Name: 'Adara Madden',
    Country: 'Pakistan',
    Age: 35,
    Gender: 'male',
    Compensation: 68706,
  },
  {
    Name: 'Fletcher Wallace',
    Country: 'Armenia',
    Age: 27,
    Gender: 'male',
    Compensation: 82954,
  },
  {
    Name: 'Sheila Melendez',
    Country: 'South Georgia and The South Sandwich Islands',
    Age: 28,
    Gender: 'male',
    Compensation: 66066,
  },
  {
    Name: 'Ira Abbott',
    Country: 'Zimbabwe',
    Age: 37,
    Gender: 'male',
    Compensation: 61606,
  }
];
